### ISSUE TITLE
和千里冰封 (ice1000) 交往几天的报告

### ISSUE THREAD

**Issue by duangsuse** [duangsuse-valid-projects/Book#5]
🌚  认识就不用说了吧 https://github.com/duangsuse/Book/issues/1

应该说, 我开始没有想到 '@' 是会有通知的 所以大概对一些与事情无关的人造成了一些影响... 抱歉
（或许这样也很唐突

这个 issue 也别拿去让冰封看了... 虽然好像公开抱怨不是很好 我不是写给冰封的 （而且发布之前我确认了他没有关注我 话说开 issue 会出现在 dashboard 上吗？）

现在我算是真正认识冰封了...
我就因为这一个人去了 QQ 然后后来又遇到各种撕...
我也加入了冰封的两个群，并且经常在群里谈笑风生...
到今天 冰封还在抱怨开始不该认识我... 应该早点把我拉黑了

这样的事情不是第一次了...

> 或许这就是大佬吧

冰封也说过他不喜欢社交（当然我也不喜欢 除非网络社交... 我觉得他这里特指真人的）
而且据我感觉恐怕 QQ 上 我几乎找不到几个友善的大佬？ (当然 也有些人不算是大佬 只要他们自己觉得是) (批评 QQ 和赞美 Telegram 冰封（还有冰封群里的几个人...）恐怕又要和我撕...)

所以说话不考虑对方的感受(傲娇)我还是可以接受的 (而且冰封性格本来就比较正常... 我是那种很虚的 讨厌在对方有理 哪怕是我也有理时撕B 这种情况我一般会道歉要求停止 每次都是这样)

~~当然 也是我的错 那样的地方不看几本书是容不下你的（笑~~
~~我有多少时间去学习呢？ 现在三线小城的高一学生 就是之前专门学了一个月 而且几乎没有书可以看(效率非常低, 因为主要的时间都在tg上社交...(现在应该好很多了 但我不知道要不要在学校留下去))~~

应该说关注 Glavo 或者说那个 中文 C# 算是 (改变了我的人生轨迹???)
好像也不是, 因为在那之前我自己选出的书就已经把我带歪了... (嗯，是我自己想入的坑
所以我有幸进入这个全是低龄大佬的圈子...

然后我由于太菜经常被大佬们吊着打和 「批判」 ...
早日成为大佬 然后利用我相对平和的性格 让以后我这种经常被大佬吊打的人能感觉到有人关怀吧...

> 或许我是对待冰封的态度不对吧？ 我一直以一个标准对待认识的朋友... 但是就 GitHub 上的项目和知乎B站的名气来说, 或许这是应该被当成大佬膜拜的 不能和 Rachel Trumeet Drakeet 一样对待？

> 那么我到底要抱怨啥呢？？？ 🌚 

+ 说的一些话真的比较伤人 (我确信我不会说出那种话 我习惯保持对方能不尴尬...)
+ 歧视 Telegram 和 GNU/Linux (其实大概是觉得我没啥技术还在这些 “肤浅” 的东西上 装B 了吧... 而且还问了 不要 最好的 C++ IDE 怎么调试 Android Naive 程序 和 AS 的 Instance Run 快捷键证明 我是小白 🌚  我的电脑真跑得起 Android Studio 吗？  

> 很抱歉我要在这里吐一下...
> 我卖一下弱吧 当然被批评是我自己找的 我至少得有他们一半技术才能闲聊技术, 是吧
> http://ice1000.org/2018/01/07/YesYesYesOhMyGod/
> 我要卖的当然是时间弱. 我比较喜欢了解我比较想了解的人(废话) 所以我非常自然的翻了冰封的空间...
> 首先我开始接触真·技术是在大概小学五年级(大概吧) 虽然是垃圾的尝试
> 大概几个月后我认识了 GNU/Linux 坑 百度 Linux 吧 然后自然完全在玩 GNU/Linux ... 一直玩到了初三的寒假 
那时候是多远呢，可能现在还只有大约一年吧... 好了, 冰封自己有博文表明，他至少开始了两年 http://ice1000.org/2017/08/30/HowTimeFlies/
比我多不知道多少时间 和多少本书都是在开始学的时候就在看的...

![2018-01-17 20-02-09](https://user-images.githubusercontent.com/10570123/35041882-510ca434-fbc1-11e7-928d-d2833b0dc7d7.png)

电脑都写没电了 🌚 
比较语无伦次 算了
我就是抱怨一下 只要有大佬接纳我我怎么会拉黑别人？

抱怨完了

**Comment by duangsuse** [comment]
无bug了。

我总是说 QQ 上的人不管小白大佬都喜欢kick

和冰封在一起的时候总是互相伤害
现在也算是眼不见心不烦了

好好搞GA吧

**Comment by ice1000** [comment]
> 我总是说 QQ 上的人不管小白大佬都喜欢kick

爱用不用

**Comment by ice1000** [comment]
什么垃圾东西。你居然还另外开了issue。

**Comment by Fun007fun** [comment]
> 好好搞GA吧

GA 是啥子

**Comment by Fun007fun** [comment]
> > 我总是说 QQ 上的人不管小白大佬都喜欢kick


### kick是指啥

**Comment by jellyterra** [comment]
发生啥事，俩人爆成这样？（

**Comment by ice1000** [comment]
> 发生啥事，俩人爆成这样？（

这都七年前的事情了，双方当年为人处世都有很多不成熟的地方。原 po 因为我使用 Windows 编程（因为主要写 Java）、使用 QQ 交流技术而反复揶揄我，说 windows 是 _losedog_，说 Windows 平台封闭，所以我不应该用 Windows，说 telegram 上大佬比 qq 多，所以我不应该用 qq。我认为这明显是对我的骚扰，因为用什么技术、和什么人交流完全是我的自由，凭什么由他来指手画脚。所以我在反复理性讨论无法让他意识到他管不到我的工作流后，非常不耐烦，对他重拳出击，对他说了很多不礼貌的话。如果换做现在的我，我会直接拉黑他，不会给他让我不耐烦的机会。

不过这么多年过去了，他现在成了 gpt 魔怔人，认为 AI 已经能学到真正的知识，身为 Kotlin 电报群宠（没错他所谓高端的电报群的群友也没把他的技术观点当回事）每天只会复读自己不知道怎么实现的基于 yaml 语法的编程语言，认为其高端至极。

不过这也只是我的一家之言，你要是有兴趣知道楼主的言行可以去 Kotlin 中文电报群围观楼主，抑郁的时候看他被喷挺解压的。
